#%RAML 1.0 ResourceType
value:
-
  id: "1"
  Name: "Max"
  address: "28404, Novi"
  accountcreationDate?: 2023-05-09T12:00:01.000Z
  type: checking
-
  id: "2"
  Name: "Morgan"
  address: "26745, Beacon Hills"
  accountcreationDate?: 2023-05-09T11:00:01.000Z
  type: saving