#%RAML 1.0 Trait
responses:
  200:
    body:
      application/json:
        example: |
         {
          "success": true,
          "reason": "Created account data" 
          example: !include examples/accountsExample.raml         
         }

  404:
    body:
      application/json:
        example: |
         {
          "success": false
          "reason": "Error retrieving account info"
         }

  201:
    body:
      application/json:
        example: {
          message: "Account created"
        }

  400:
    body:
      application/json:
        example: {
          message: "Error creating account, verify is data valid"
        }
            
        